# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestGiu():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
    self.driver.implicitly_wait(5)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_giu(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, "#perfil-hidden > .iconav").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.ID, "ContentSite_ibtNewCustomer").click()
    self.driver.find_element(By.ID, "ContentSite_txtName").send_keys("João Mota da Silva")
    self.driver.find_element(By.ID, "ContentSite_txtCpf").send_keys("536.652.040-11")
    self.driver.find_element(By.ID, "ContentSite_txtEmail").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("testejju@uorak.com")
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1)").click()
    self.driver.find_element(By.ID, "ContentSite_txtPasswordNew").send_keys("iRDbAbqq87e1")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtZip").send_keys("05734-080")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtAddressNumber").send_keys("55")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtComplement").send_keys("AP10")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtPhoneCelularNum").send_keys("11980701508")
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    self.driver.switch_to.default_content()
    self.driver.find_element(By.ID, "ContentSite_btnCreateCustomer").click()
   
